### ISSUE TITLE
Why element wise multiplication between dilation and original?

### ISSUE THREAD

**Issue by zanklanecek** [howchihlee/COVID19_CT#2]
https://github.com/howchihlee/COVID19_CT/blob/bb247bf8c0a81a96bbdda2d7e12902bee1145a6b/pytorch_model/ct_lung_maxpool_res18/model_main_ops/datareader.py#L65

I assume, that your input image is .png format since you are usiing skimage imread. There are then 3 identical R G B channels due to gray image? So why exactly are you here performing element wise operation between original and dilated image? 

Thanks!

**Comment by denbonte** [comment]
@zanklanecek I suppose `img[:, :, 2]` stores some sort of mask, which makes the line you highlighted compute a masking between the CT slice and the aforementioned. In fact, in Figure 3 of the Nature Medicine paper you can notice the network takes as input a masked version of the CT slices.

Furthermore, if `img[:, :, 2]` didn't store a mask, the dilation operation (at the line that precedes the one you highlighted) would not make sense in the first place.

**Comment by zanklanecek** [comment]
Ye this would make sense. However, I am not so sure why this would need to be calculated in each epoch and not as a step of pre-processing the data. Thanks though!

**Comment by denbonte** [comment]
> However, I am not so sure why this would need to be calculated in each epoch and not as a step of pre-processing the data.

Good point. Probably just a choice? Honestly, I cannot see the learning being slowed down that much by this additional operation in the data loader. But maybe they have got a further explanation.


> Thanks though!

No problem!

**Comment by zanklanecek** [comment]
There is also a datareader.py without this step in _model_init_ops_ folder. Interesting.

**Comment by howchihlee** [comment]
Yes we store images in channel 1 and masks in other channels. The masked images can certainly be precomputed and stored to save computation but it is just handy to do it this way as we were testing different ways to mask the images.

There is no masking in model_init_ops because different images, extracted patches instead of the raw images, were used for initialization.
